app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

nvms_api:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/api-routing.yml"

rssatom:
    resource: "@DebrilRssAtomBundle/Resources/config/routing.xml"
