<?php

namespace CoreBundle\Repository;

/**
 * UserRssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRssRepository extends \Doctrine\ORM\EntityRepository
{
}
